# -*- coding: utf-8 -*-
"""
Plantilla base de una auditoría IT para una nueva fábrica u oficina,
disponible en español (es), inglés (en) e italiano (it).

`build_template(lang)` devuelve la lista de secciones ya traducida. Cada sección
se materializa como una fila `Section` al crear una auditoría, y cada ítem como
una fila `Item` (estado inicial `pendiente`). El idioma se fija al crear la
auditoría; el texto que el usuario edite después se conserva tal cual.
"""

LANGS = ("es", "en", "it")
DEFAULT_LANG = "es"


def _t(es, en, it):
    return {"es": es, "en": en, "it": it}


_SECTIONS = [
    {
        "key": "infra_fisica",
        "title": _t(
            "Infraestructura física / CPD",
            "Physical infrastructure / Data center",
            "Infrastruttura fisica / Data center",
        ),
        "description": _t(
            "Sala técnica, rack, alimentación, climatización y acceso físico.",
            "Server room, racks, power, cooling and physical access.",
            "Sala tecnica, rack, alimentazione, climatizzazione e accesso fisico.",
        ),
        "items": [
            _t("Ubicación y dimensiones de la sala técnica / CPD",
               "Location and size of the server room / data center",
               "Ubicazione e dimensioni della sala tecnica / data center"),
            _t("Racks: cantidad, unidades libres, anclaje y organización",
               "Racks: quantity, free units, anchoring and layout",
               "Rack: quantità, unità libere, ancoraggio e organizzazione"),
            _t("SAI / UPS: potencia, autonomía y estado de baterías",
               "UPS: capacity, runtime and battery condition",
               "UPS: potenza, autonomia e stato delle batterie"),
            _t("Grupo electrógeno / línea eléctrica dedicada y protección",
               "Generator / dedicated power line and protection",
               "Gruppo elettrogeno / linea elettrica dedicata e protezione"),
            _t("Climatización: equipos, redundancia y control de temperatura/humedad",
               "Cooling: units, redundancy and temperature/humidity control",
               "Climatizzazione: unità, ridondanza e controllo di temperatura/umidità"),
            _t("Cuadro eléctrico dedicado y tomas por rack (monofásico/trifásico)",
               "Dedicated electrical panel and outlets per rack (single/three-phase)",
               "Quadro elettrico dedicato e prese per rack (monofase/trifase)"),
            _t("Detección y extinción de incendios",
               "Fire detection and suppression",
               "Rilevazione e spegnimento incendi"),
            _t("Control de acceso físico a la sala (cerradura, registro, CCTV)",
               "Physical access control to the room (lock, log, CCTV)",
               "Controllo accessi fisici alla sala (serratura, registro, CCTV)"),
            _t("Etiquetado de racks, tomas y latiguillos",
               "Labelling of racks, outlets and patch cords",
               "Etichettatura di rack, prese e patch cord"),
        ],
    },
    {
        "key": "red",
        "title": _t("Red y comunicaciones", "Network and communications", "Rete e comunicazioni"),
        "description": _t(
            "Electrónica de red, direccionamiento, WiFi y salida a internet.",
            "Network hardware, addressing, WiFi and internet access.",
            "Apparati di rete, indirizzamento, WiFi e accesso a internet.",
        ),
        "items": [
            _t("Inventario de switches (modelo, puertos, PoE, firmware, gestión)",
               "Switch inventory (model, ports, PoE, firmware, management)",
               "Inventario switch (modello, porte, PoE, firmware, gestione)"),
            _t("Router / firewall perimetral: modelo, licencias y alta disponibilidad",
               "Perimeter router / firewall: model, licences and high availability",
               "Router / firewall perimetrale: modello, licenze e alta disponibilità"),
            _t("Esquema de VLANs y segmentación (datos, voz, OT, invitados, gestión)",
               "VLAN scheme and segmentation (data, voice, OT, guest, management)",
               "Schema VLAN e segmentazione (dati, voce, OT, ospiti, gestione)"),
            _t("Plan de direccionamiento IP y DHCP",
               "IP addressing plan and DHCP",
               "Piano di indirizzamento IP e DHCP"),
            _t("Enlaces troncales y uplinks (velocidad, agregación, redundancia)",
               "Trunk links and uplinks (speed, aggregation, redundancy)",
               "Collegamenti trunk e uplink (velocità, aggregazione, ridondanza)"),
            _t("Cobertura y controladora WiFi (SSIDs, seguridad, roaming)",
               "WiFi coverage and controller (SSIDs, security, roaming)",
               "Copertura e controller WiFi (SSID, sicurezza, roaming)"),
            _t("Líneas WAN / ISP: operador, caudal, SLA y router de respaldo",
               "WAN / ISP lines: carrier, bandwidth, SLA and backup router",
               "Linee WAN / ISP: operatore, banda, SLA e router di backup"),
            _t("DNS interno/externo y publicación de servicios",
               "Internal/external DNS and service publishing",
               "DNS interno/esterno e pubblicazione dei servizi"),
            _t("Documentación: diagrama de red lógico y físico",
               "Documentation: logical and physical network diagram",
               "Documentazione: diagramma di rete logico e fisico"),
        ],
    },
    {
        "key": "cableado",
        "title": _t("Cableado estructurado", "Structured cabling", "Cablaggio strutturato"),
        "description": _t(
            "Cobre, fibra, canalizaciones, certificación y etiquetado.",
            "Copper, fibre, trunking, certification and labelling.",
            "Rame, fibra, canaline, certificazione ed etichettatura.",
        ),
        "items": [
            _t("Categoría de cableado horizontal (Cat6/6A) y número de tomas por puesto",
               "Horizontal cabling category (Cat6/6A) and number of outlets per workstation",
               "Categoria del cablaggio orizzontale (Cat6/6A) e numero di prese per postazione"),
            _t("Backbone de fibra entre repartidores (tipo, hilos, conectorización)",
               "Fibre backbone between distributors (type, strands, connectors)",
               "Dorsale in fibra tra i distributori (tipo, fili, connettorizzazione)"),
            _t("Repartidores (RITI/RITS/rack de planta): ubicación y capacidad",
               "Distributors (main / floor racks): location and capacity",
               "Distributori (rack principale / di piano): ubicazione e capacità"),
            _t("Canalizaciones, bandejas y separación de eléctrica",
               "Trunking, trays and separation from power cabling",
               "Canaline, passerelle e separazione dall'impianto elettrico"),
            _t("Certificación de enlaces (informe del certificador)",
               "Link certification (certifier report)",
               "Certificazione dei collegamenti (report del certificatore)"),
            _t("Etiquetado normalizado de tomas, paneles y latiguillos",
               "Standardised labelling of outlets, panels and patch cords",
               "Etichettatura standardizzata di prese, pannelli e patch cord"),
            _t("Planos de rosetas y trazado por planta",
               "Outlet plans and routing per floor",
               "Planimetria delle prese e percorsi per piano"),
            _t("Tomas para APs, cámaras, control de acceso y máquinas de planta",
               "Outlets for APs, cameras, access control and shop-floor machines",
               "Prese per AP, telecamere, controllo accessi e macchine di produzione"),
        ],
    },
    {
        "key": "puestos",
        "title": _t("Puestos de usuario", "User workstations", "Postazioni di lavoro"),
        "description": _t(
            "PCs, portátiles, periféricos, imagen del SO e inventario.",
            "PCs, laptops, peripherals, OS image and inventory.",
            "PC, portatili, periferiche, immagine del SO e inventario.",
        ),
        "items": [
            _t("Inventario de equipos (PC/portátil) por usuario y ubicación",
               "Device inventory (PC/laptop) per user and location",
               "Inventario dei dispositivi (PC/portatile) per utente e sede"),
            _t("Modelo estándar y ciclo de renovación",
               "Standard model and refresh cycle",
               "Modello standard e ciclo di rinnovo"),
            _t("Imagen / despliegue del SO y aplicaciones base",
               "OS image / deployment and base applications",
               "Immagine / deployment del SO e applicazioni di base"),
            _t("Monitores, docks y periféricos",
               "Monitors, docks and peripherals",
               "Monitor, dock e periferiche"),
            _t("Impresoras y escáneres (red, colas, drivers)",
               "Printers and scanners (network, queues, drivers)",
               "Stampanti e scanner (rete, code, driver)"),
            _t("Telefonía IP / softphone en el puesto",
               "IP telephony / softphone at the desk",
               "Telefonia IP / softphone sulla postazione"),
            _t("Cifrado de disco (BitLocker/FileVault) y bloqueo de sesión",
               "Disk encryption (BitLocker/FileVault) and session lock",
               "Cifratura del disco (BitLocker/FileVault) e blocco sessione"),
            _t("Gestión de parches y agente de inventario",
               "Patch management and inventory agent",
               "Gestione patch e agente di inventario"),
        ],
    },
    {
        "key": "servidores",
        "title": _t("Servidores y virtualización", "Servers and virtualisation", "Server e virtualizzazione"),
        "description": _t(
            "Hardware físico, hipervisor, sistemas operativos y dimensionamiento.",
            "Physical hardware, hypervisor, operating systems and sizing.",
            "Hardware fisico, hypervisor, sistemi operativi e dimensionamento.",
        ),
        "items": [
            _t("Inventario de servidores físicos (modelo, CPU, RAM, discos, garantía)",
               "Physical server inventory (model, CPU, RAM, disks, warranty)",
               "Inventario dei server fisici (modello, CPU, RAM, dischi, garanzia)"),
            _t("Hipervisor (VMware/Hyper-V/Proxmox): versión y licencias",
               "Hypervisor (VMware/Hyper-V/Proxmox): version and licences",
               "Hypervisor (VMware/Hyper-V/Proxmox): versione e licenze"),
            _t("Inventario de máquinas virtuales y su función",
               "Virtual machine inventory and their role",
               "Inventario delle macchine virtuali e loro funzione"),
            _t("Dimensionamiento y margen de crecimiento (CPU/RAM/disco)",
               "Sizing and headroom for growth (CPU/RAM/disk)",
               "Dimensionamento e margine di crescita (CPU/RAM/disco)"),
            _t("Alta disponibilidad / clustering",
               "High availability / clustering",
               "Alta disponibilità / clustering"),
            _t("Monitorización de hardware (iLO/iDRAC) y alertas",
               "Hardware monitoring (iLO/iDRAC) and alerts",
               "Monitoraggio hardware (iLO/iDRAC) e avvisi"),
            _t("Sistemas operativos: versiones y soporte vigente",
               "Operating systems: versions and active support",
               "Sistemi operativi: versioni e supporto attivo"),
            _t("Servidores en la nube / híbrido (si aplica)",
               "Cloud / hybrid servers (if applicable)",
               "Server in cloud / ibridi (se applicabile)"),
        ],
    },
    {
        "key": "backup",
        "title": _t("Almacenamiento y copias de seguridad", "Storage and backups", "Storage e backup"),
        "description": _t(
            "Cabinas, NAS, política de backup, retención y pruebas de restauración.",
            "Arrays, NAS, backup policy, retention and restore tests.",
            "Storage array, NAS, policy di backup, retention e test di ripristino.",
        ),
        "items": [
            _t("Almacenamiento compartido (NAS/SAN): capacidad, RAID y estado",
               "Shared storage (NAS/SAN): capacity, RAID and health",
               "Storage condiviso (NAS/SAN): capacità, RAID e stato"),
            _t("Software de backup y alcance (VMs, ficheros, bases de datos, endpoints)",
               "Backup software and scope (VMs, files, databases, endpoints)",
               "Software di backup e ambito (VM, file, database, endpoint)"),
            _t("Política 3-2-1: copia local, copia externa y copia offline/inmutable",
               "3-2-1 policy: local copy, offsite copy and offline/immutable copy",
               "Policy 3-2-1: copia locale, copia esterna e copia offline/immutabile"),
            _t("Calendario de copias y ventanas",
               "Backup schedule and windows",
               "Calendario dei backup e finestre"),
            _t("Retención (diaria/semanal/mensual/anual)",
               "Retention (daily/weekly/monthly/yearly)",
               "Retention (giornaliera/settimanale/mensile/annuale)"),
            _t("Cifrado de las copias", "Backup encryption", "Cifratura dei backup"),
            _t("Última prueba de restauración documentada",
               "Last documented restore test",
               "Ultimo test di ripristino documentato"),
            _t("Monitorización y alertas de trabajos fallidos",
               "Monitoring and alerts for failed jobs",
               "Monitoraggio e avvisi per job falliti"),
        ],
    },
    {
        "key": "software",
        "title": _t("Software y licencias", "Software and licensing", "Software e licenze"),
        "description": _t(
            "Sistemas operativos, ofimática, ERP/MES, seguridad e inventario de licencias.",
            "Operating systems, office suite, ERP/MES, security and licence inventory.",
            "Sistemi operativi, suite per ufficio, ERP/MES, sicurezza e inventario licenze.",
        ),
        "items": [
            _t("Inventario de software y versión por equipo/servidor",
               "Software inventory and version per device/server",
               "Inventario software e versione per dispositivo/server"),
            _t("Licenciamiento de SO y ofimática (tipo, cantidad, vencimiento)",
               "OS and office licensing (type, quantity, expiry)",
               "Licenze SO e ufficio (tipo, quantità, scadenza)"),
            _t("ERP / MES / SCADA: versión, soporte y responsable",
               "ERP / MES / SCADA: version, support and owner",
               "ERP / MES / SCADA: versione, supporto e responsabile"),
            _t("Antivirus / EDR: consola, cobertura y estado",
               "Antivirus / EDR: console, coverage and status",
               "Antivirus / EDR: console, copertura e stato"),
            _t("Aplicaciones específicas de planta / laboratorio",
               "Plant / lab-specific applications",
               "Applicazioni specifiche di stabilimento / laboratorio"),
            _t("Política de software permitido y bloqueo de instalaciones",
               "Allowed-software policy and installation lockdown",
               "Policy sul software consentito e blocco delle installazioni"),
            _t("Contratos de mantenimiento y renovaciones de licencia",
               "Maintenance contracts and licence renewals",
               "Contratti di manutenzione e rinnovi delle licenze"),
        ],
    },
    {
        "key": "seguridad",
        "title": _t("Seguridad", "Security", "Sicurezza"),
        "description": _t(
            "Identidades, accesos, segmentación, hardening y parcheado.",
            "Identities, access, segmentation, hardening and patching.",
            "Identità, accessi, segmentazione, hardening e patching.",
        ),
        "items": [
            _t("Política de contraseñas y gestor de credenciales",
               "Password policy and credential manager",
               "Policy delle password e gestore delle credenziali"),
            _t("MFA en accesos críticos (VPN, correo, administración)",
               "MFA on critical access (VPN, email, administration)",
               "MFA sugli accessi critici (VPN, posta, amministrazione)"),
            _t("Cuentas de administración: inventario y uso de cuentas nominales",
               "Admin accounts: inventory and use of named accounts",
               "Account amministrativi: inventario e uso di account nominali"),
            _t("Segmentación IT/OT y reglas de firewall documentadas",
               "IT/OT segmentation and documented firewall rules",
               "Segmentazione IT/OT e regole firewall documentate"),
            _t("VPN de acceso remoto: método y control",
               "Remote-access VPN: method and control",
               "VPN di accesso remoto: metodo e controllo"),
            _t("Gestión de parches de seguridad (SO y aplicaciones)",
               "Security patch management (OS and applications)",
               "Gestione delle patch di sicurezza (SO e applicazioni)"),
            _t("Hardening de servidores, red y puestos",
               "Hardening of servers, network and workstations",
               "Hardening di server, rete e postazioni"),
            _t("Registro y revisión de logs (SIEM / syslog)",
               "Log collection and review (SIEM / syslog)",
               "Raccolta e revisione dei log (SIEM / syslog)"),
            _t("Plan de respuesta ante incidentes y contactos",
               "Incident response plan and contacts",
               "Piano di risposta agli incidenti e contatti"),
            _t("Cumplimiento aplicable (ENS, ISO 27001, RGPD) según corresponda",
               "Applicable compliance (ISO 27001, GDPR, NIS2) as relevant",
               "Conformità applicabile (ISO 27001, GDPR, NIS2) secondo il caso"),
        ],
    },
    {
        "key": "servicios",
        "title": _t("Servicios y aplicaciones", "Services and applications", "Servizi e applicazioni"),
        "description": _t(
            "Directorio, correo, ERP, impresión, telefonía y otros servicios comunes.",
            "Directory, email, ERP, printing, telephony and other common services.",
            "Directory, posta, ERP, stampa, telefonia e altri servizi comuni.",
        ),
        "items": [
            _t("Directorio activo / IdP: dominios, controladores y replicación",
               "Active Directory / IdP: domains, controllers and replication",
               "Active Directory / IdP: domini, controller e replica"),
            _t("Correo electrónico (on-premise / cloud) y dominios",
               "Email (on-premise / cloud) and domains",
               "Posta elettronica (on-premise / cloud) e domini"),
            _t("Servidor de ficheros y estructura de permisos",
               "File server and permission structure",
               "File server e struttura dei permessi"),
            _t("Servicio de impresión y contabilidad de copias",
               "Print service and print accounting",
               "Servizio di stampa e contabilizzazione delle copie"),
            _t("Telefonía / centralita IP y numeración",
               "Telephony / IP PBX and numbering",
               "Telefonia / centralino IP e numerazione"),
            _t("DHCP/DNS/NTP internos", "Internal DHCP/DNS/NTP", "DHCP/DNS/NTP interni"),
            _t("Portal / intranet y aplicaciones web internas",
               "Portal / intranet and internal web applications",
               "Portale / intranet e applicazioni web interne"),
            _t("Integraciones con sistemas de planta (fichaje, accesos, MES)",
               "Integrations with plant systems (time & attendance, access, MES)",
               "Integrazioni con i sistemi di stabilimento (rilevazione presenze, accessi, MES)"),
        ],
    },
    {
        "key": "proveedores",
        "title": _t("Proveedores y contratos", "Vendors and contracts", "Fornitori e contratti"),
        "description": _t(
            "Operadores, mantenimiento, soporte, SLAs y contactos.",
            "Carriers, maintenance, support, SLAs and contacts.",
            "Operatori, manutenzione, supporto, SLA e contatti.",
        ),
        "items": [
            _t("ISP / operador WAN: contrato, caudal, SLA y contacto de averías",
               "ISP / WAN carrier: contract, bandwidth, SLA and fault contact",
               "ISP / operatore WAN: contratto, banda, SLA e contatto guasti"),
            _t("Mantenimiento de hardware (servidores, red, SAI): alcance y tiempos",
               "Hardware maintenance (servers, network, UPS): scope and response times",
               "Manutenzione hardware (server, rete, UPS): ambito e tempi di intervento"),
            _t("Soporte de software crítico (ERP/MES) y ventanas de atención",
               "Critical software support (ERP/MES) and support hours",
               "Supporto software critico (ERP/MES) e orari di assistenza"),
            _t("Proveedor de cableado / obra y garantía de la instalación",
               "Cabling / works contractor and installation warranty",
               "Fornitore del cablaggio / opere e garanzia dell'installazione"),
            _t("Proveedor de seguridad gestionada / SOC (si aplica)",
               "Managed security / SOC provider (if applicable)",
               "Fornitore di sicurezza gestita / SOC (se applicabile)"),
            _t("Servicios cloud contratados y responsables",
               "Contracted cloud services and owners",
               "Servizi cloud attivati e responsabili"),
            _t("Matriz de contactos y escalado (24x7 vs horario laboral)",
               "Contact and escalation matrix (24x7 vs business hours)",
               "Matrice dei contatti ed escalation (24x7 vs orario lavorativo)"),
            _t("Inventario de contratos con fechas de renovación",
               "Contract inventory with renewal dates",
               "Inventario dei contratti con date di rinnovo"),
        ],
    },
    {
        "key": "continuidad",
        "title": _t("Continuidad y recuperación", "Continuity and recovery", "Continuità e ripristino"),
        "description": _t(
            "Plan de recuperación ante desastres, redundancias y objetivos RTO/RPO.",
            "Disaster recovery plan, redundancy and RTO/RPO objectives.",
            "Piano di disaster recovery, ridondanze e obiettivi RTO/RPO.",
        ),
        "items": [
            _t("Análisis de servicios críticos y su prioridad de recuperación",
               "Analysis of critical services and their recovery priority",
               "Analisi dei servizi critici e loro priorità di ripristino"),
            _t("Objetivos RTO / RPO acordados con negocio",
               "RTO / RPO targets agreed with the business",
               "Obiettivi RTO / RPO concordati con il business"),
            _t("Redundancias (energía, climatización, WAN, electrónica de red)",
               "Redundancy (power, cooling, WAN, network hardware)",
               "Ridondanze (alimentazione, climatizzazione, WAN, apparati di rete)"),
            _t("Procedimiento de recuperación documentado y probado",
               "Documented and tested recovery procedure",
               "Procedura di ripristino documentata e testata"),
            _t("Emplazamiento alternativo / copia externa para recuperación",
               "Alternative site / offsite copy for recovery",
               "Sito alternativo / copia esterna per il ripristino"),
            _t("Simulacro de contingencia realizado y fecha",
               "Contingency drill performed and date",
               "Esercitazione di continuità svolta e data"),
        ],
    },
    {
        "key": "documentacion",
        "title": _t("Documentación y entrega", "Documentation and handover", "Documentazione e consegna"),
        "description": _t(
            "Planos, inventarios, credenciales, diagramas y manuales entregados.",
            "Plans, inventories, credentials, diagrams and manuals delivered.",
            "Planimetrie, inventari, credenziali, diagrammi e manuali consegnati.",
        ),
        "items": [
            _t("Diagrama de red lógico y físico actualizado",
               "Up-to-date logical and physical network diagram",
               "Diagramma di rete logico e fisico aggiornato"),
            _t("Inventario de activos (hardware, software, licencias)",
               "Asset inventory (hardware, software, licences)",
               "Inventario degli asset (hardware, software, licenze)"),
            _t("Planos de cableado y certificaciones",
               "Cabling plans and certifications",
               "Planimetrie del cablaggio e certificazioni"),
            _t("Custodia de credenciales de administración",
               "Safekeeping of administration credentials",
               "Custodia delle credenziali di amministrazione"),
            _t("Procedimientos de operación y runbooks",
               "Operating procedures and runbooks",
               "Procedure operative e runbook"),
            _t("Contratos y garantías archivados",
               "Contracts and warranties on file",
               "Contratti e garanzie archiviati"),
            _t("Acta de entrega y aceptación de la infraestructura",
               "Infrastructure handover and acceptance record",
               "Verbale di consegna e accettazione dell'infrastruttura"),
            _t("Formación / traspaso al equipo de soporte",
               "Training / handover to the support team",
               "Formazione / passaggio di consegne al team di supporto"),
        ],
    },
]


def build_template(lang=DEFAULT_LANG):
    """Devuelve la plantilla de secciones/ítems traducida al idioma pedido."""
    if lang not in LANGS:
        lang = DEFAULT_LANG
    result = []
    for section in _SECTIONS:
        result.append({
            "key": section["key"],
            "title": section["title"][lang],
            "description": section["description"][lang],
            "items": [item[lang] for item in section["items"]],
        })
    return result
