# -*- coding: utf-8 -*-
"""
Plantilla base de una auditoría IT para una nueva fábrica u oficina.

Cada sección se materializa como una fila `Section` al crear una auditoría, y
cada cadena de `items` se materializa como una fila `Item` (estado inicial
`pendiente`). A partir de ahí el usuario añade / edita / borra libremente.
"""

AUDIT_TEMPLATE = [
    {
        "key": "infra_fisica",
        "title": "Infraestructura física / CPD",
        "description": "Sala técnica, rack, alimentación, climatización y acceso físico.",
        "items": [
            "Ubicación y dimensiones de la sala técnica / CPD",
            "Racks: cantidad, unidades libres, anclaje y organización",
            "SAI / UPS: potencia, autonomía y estado de baterías",
            "Grupo electrógeno / línea eléctrica dedicada y protección",
            "Climatización: equipos, redundancia y control de temperatura/humedad",
            "Cuadro eléctrico dedicado y tomas por rack (monofásico/trifásico)",
            "Detección y extinción de incendios",
            "Control de acceso físico a la sala (cerradura, registro, CCTV)",
            "Etiquetado de racks, tomas y latiguillos",
        ],
    },
    {
        "key": "red",
        "title": "Red y comunicaciones",
        "description": "Electrónica de red, direccionamiento, WiFi y salida a internet.",
        "items": [
            "Inventario de switches (modelo, puertos, PoE, firmware, gestión)",
            "Router / firewall perimetral: modelo, licencias y alta disponibilidad",
            "Esquema de VLANs y segmentación (datos, voz, OT, invitados, gestión)",
            "Plan de direccionamiento IP y DHCP",
            "Enlaces troncales y uplinks (velocidad, agregación, redundancia)",
            "Cobertura y controladora WiFi (SSIDs, seguridad, roaming)",
            "Líneas WAN / ISP: operador, caudal, SLA y router de respaldo",
            "DNS interno/externo y publicación de servicios",
            "Documentación: diagrama de red lógico y físico",
        ],
    },
    {
        "key": "cableado",
        "title": "Cableado estructurado",
        "description": "Cobre, fibra, canalizaciones, certificación y etiquetado.",
        "items": [
            "Categoría de cableado horizontal (Cat6/6A) y número de tomas por puesto",
            "Backbone de fibra entre repartidores (tipo, hilos, conectorización)",
            "Repartidores (RITI/RITS/rack de planta): ubicación y capacidad",
            "Canalizaciones, bandejas y separación de eléctrica",
            "Certificación de enlaces (informe del certificador)",
            "Etiquetado normalizado de tomas, paneles y latiguillos",
            "Planos de rosetas y trazado por planta",
            "Tomas para APs, cámaras, control de acceso y máquinas de planta",
        ],
    },
    {
        "key": "puestos",
        "title": "Puestos de usuario",
        "description": "PCs, portátiles, periféricos, imagen del SO e inventario.",
        "items": [
            "Inventario de equipos (PC/portátil) por usuario y ubicación",
            "Modelo estándar y ciclo de renovación",
            "Imagen / despliegue del SO y aplicaciones base",
            "Monitores, docks y periféricos",
            "Impresoras y escáneres (red, colas, drivers)",
            "Telefonía IP / softphone en el puesto",
            "Cifrado de disco (BitLocker/FileVault) y bloqueo de sesión",
            "Gestión de parches y agente de inventario",
        ],
    },
    {
        "key": "servidores",
        "title": "Servidores y virtualización",
        "description": "Hardware físico, hipervisor, sistemas operativos y dimensionamiento.",
        "items": [
            "Inventario de servidores físicos (modelo, CPU, RAM, discos, garantía)",
            "Hipervisor (VMware/Hyper-V/Proxmox): versión y licencias",
            "Inventario de máquinas virtuales y su función",
            "Dimensionamiento y margen de crecimiento (CPU/RAM/disco)",
            "Alta disponibilidad / clustering",
            "Monitorización de hardware (iLO/iDRAC) y alertas",
            "Sistemas operativos: versiones y soporte vigente",
            "Servidores en la nube / híbrido (si aplica)",
        ],
    },
    {
        "key": "backup",
        "title": "Almacenamiento y copias de seguridad",
        "description": "Cabinas, NAS, política de backup, retención y pruebas de restauración.",
        "items": [
            "Almacenamiento compartido (NAS/SAN): capacidad, RAID y estado",
            "Software de backup y alcance (VMs, ficheros, bases de datos, endpoints)",
            "Política 3-2-1: copia local, copia externa y copia offline/inmutable",
            "Calendario de copias y ventanas",
            "Retención (diaria/semanal/mensual/anual)",
            "Cifrado de las copias",
            "Última prueba de restauración documentada",
            "Monitorización y alertas de trabajos fallidos",
        ],
    },
    {
        "key": "software",
        "title": "Software y licencias",
        "description": "Sistemas operativos, ofimática, ERP/MES, seguridad e inventario de licencias.",
        "items": [
            "Inventario de software y versión por equipo/servidor",
            "Licenciamiento de SO y ofimática (tipo, cantidad, vencimiento)",
            "ERP / MES / SCADA: versión, soporte y responsable",
            "Antivirus / EDR: consola, cobertura y estado",
            "Aplicaciones específicas de planta / laboratorio",
            "Política de software permitido y bloqueo de instalaciones",
            "Contratos de mantenimiento y renovaciones de licencia",
        ],
    },
    {
        "key": "seguridad",
        "title": "Seguridad",
        "description": "Identidades, accesos, segmentación, hardening y parcheado.",
        "items": [
            "Política de contraseñas y gestor de credenciales",
            "MFA en accesos críticos (VPN, correo, administración)",
            "Cuentas de administración: inventario y uso de cuentas nominales",
            "Segmentación IT/OT y reglas de firewall documentadas",
            "VPN de acceso remoto: método y control",
            "Gestión de parches de seguridad (SO y aplicaciones)",
            "Hardening de servidores, red y puestos",
            "Registro y revisión de logs (SIEM / syslog)",
            "Plan de respuesta ante incidentes y contactos",
            "Cumplimiento aplicable (ENS, ISO 27001, RGPD) según corresponda",
        ],
    },
    {
        "key": "servicios",
        "title": "Servicios y aplicaciones",
        "description": "Directorio, correo, ERP, impresión, telefonía y otros servicios comunes.",
        "items": [
            "Directorio activo / IdP: dominios, controladores y replicación",
            "Correo electrónico (on-premise / cloud) y dominios",
            "Servidor de ficheros y estructura de permisos",
            "Servicio de impresión y contabilidad de copias",
            "Telefonía / centralita IP y numeración",
            "DHCP/DNS/NTP internos",
            "Portal / intranet y aplicaciones web internas",
            "Integraciones con sistemas de planta (fichaje, accesos, MES)",
        ],
    },
    {
        "key": "proveedores",
        "title": "Proveedores y contratos",
        "description": "Operadores, mantenimiento, soporte, SLAs y contactos.",
        "items": [
            "ISP / operador WAN: contrato, caudal, SLA y contacto de averías",
            "Mantenimiento de hardware (servidores, red, SAI): alcance y tiempos",
            "Soporte de software crítico (ERP/MES) y ventanas de atención",
            "Proveedor de cableado / obra y garantía de la instalación",
            "Proveedor de seguridad gestionada / SOC (si aplica)",
            "Servicios cloud contratados y responsables",
            "Matriz de contactos y escalado (24x7 vs horario laboral)",
            "Inventario de contratos con fechas de renovación",
        ],
    },
    {
        "key": "continuidad",
        "title": "Continuidad y recuperación",
        "description": "Plan de recuperación ante desastres, redundancias y objetivos RTO/RPO.",
        "items": [
            "Análisis de servicios críticos y su prioridad de recuperación",
            "Objetivos RTO / RPO acordados con negocio",
            "Redundancias (energía, climatización, WAN, electrónica de red)",
            "Procedimiento de recuperación documentado y probado",
            "Emplazamiento alternativo / copia externa para recuperación",
            "Simulacro de contingencia realizado y fecha",
        ],
    },
    {
        "key": "documentacion",
        "title": "Documentación y entrega",
        "description": "Planos, inventarios, credenciales, diagramas y manuales entregados.",
        "items": [
            "Diagrama de red lógico y físico actualizado",
            "Inventario de activos (hardware, software, licencias)",
            "Planos de cableado y certificaciones",
            "Custodia de credenciales de administración",
            "Procedimientos de operación y runbooks",
            "Contratos y garantías archivados",
            "Acta de entrega y aceptación de la infraestructura",
            "Formación / traspaso al equipo de soporte",
        ],
    },
]
